### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by alexgleason** [esroyo/scoped-performance#1]
Hi, thank you for this great library! It helped me a lot for finding slow queries. But sometimes, under certain conditions I don't understand, the library itself seems to contribute to slowing down my code.

Check this one, for instance. 5.85ms of `measure`:

![image](https://github.com/esroyo/scoped-performance/assets/3639540/92e5ddae-1ade-4717-9149-5bc584802bd7)

It seems to add up, and often calling `measure` takes more time than the query itself:

![image](https://github.com/esroyo/scoped-performance/assets/3639540/3f7d23bf-40b3-4cb5-99e6-3aa0ee98c33d)

However, this doesn't seem to be a problem when the process first starts... only after it has been running for a while. It it possible I have a memory leak and need to do cleanup? Here is the method I am calling:

```ts
  executeQuery<R>({ sql, parameters }: CompiledQuery): QueryResult<R> {
    if (!db) throw new Error('Database not open');

    const perf = new ScopedPerformance();
    perf.mark('start');

    const result = {
      rows: db!.prepare(sql).all(...parameters as any[]) as R[],
      numAffectedRows: BigInt(db!.changes),
      insertId: BigInt(db!.lastInsertRowId),
    };

    const { duration } = perf.measure('end', 'start');
    debug(`${sql} \x1b[90m(${(duration / 1000).toFixed(2)}s)\x1b[0m`);

    return result;
  },
```

Here is the cpuprofile so you can take a look yourself: 
[mostr-measure-highcpu.cpuprofile](https://github.com/esroyo/scoped-performance/files/14744188/mostr-measure-highcpu.cpuprofile)

You can load it into Chrome DevTools here: 
![image](https://github.com/esroyo/scoped-performance/assets/3639540/80b1b0f5-4d53-4efa-85ac-85f4072b30f0)

**Comment by alexgleason** [comment]
Hi @esroyo, can you please take a look at this?

It appears performance is suffering due to a call to Deno's performance API itself, specifically `findMostRecent`:

![image](https://github.com/esroyo/scoped-performance/assets/3639540/c22e869f-0374-4d61-8ce9-93c2c3db27f8)

![image](https://github.com/esroyo/scoped-performance/assets/3639540/16f48ef1-241b-4500-803c-cf4fbe778c02)

```ts
function findMostRecent(
  name,
  type,
) {
  return ArrayPrototypeFind(
    ArrayPrototypeReverse(ArrayPrototypeSlice(performanceEntries)),
    (entry) => entry.name === name && entry.entryType === type,
  );
}
```

This must be due to a memory leak, right? We are saving too many entries and then not clearing them, so the list gets longer and longer over time.

Is there anything we can do on our end (or within this library) to prevent that?

EDIT: Maybe I just need to call `perf.clearMarks(); perf.clearMeasures();`?

EDIT2: https://gitlab.com/soapbox-pub/ditto/-/merge_requests/141

**Comment by esroyo** [comment]
@alexgleason I'm very sorry to be this late, the notification got totally overlooked :pensive: :pray:  

Your reasoning makes every sense: if there is a problem of time accessing the given measure or mark, it must be form the underlying native Performance implementation, in this case Deno's. The only thing we can do from user-land is to make sure the given measures/marks are removed once the instance is not needed any more (as you already did).

Probably it is a good idea to implement [`Symbol.dispose`](https://www.totaltypescript.com/typescript-5-2-new-keyword-using) on the `ScopedPerformance` class, so that the clearing is done when the scope ends:

```ts
{
    using perf = new ScopedPerformance();
    perf.mark('start');

    // ...
    const { duration } = perf.measure('end', 'start');

}

// when `perf` is not accessible any more, this should happen out-of-the-box
// perf.clearMarks();
// perf.clearMeasures();
```

**Comment by esroyo** [comment]
* The upcoming Deno 2.0 release will include a improved implementation of `measure()`:
 https://github.com/denoland/deno/pull/25774
* version [3.1.0](https://github.com/esroyo/scoped-performance/blob/main/CHANGELOG.md#310-2024-09-24) of `ScopedPerformance` supports the `using` keyword, so we do not need to remember clearing the marks and measures manually.

Thanks for your report @alexgleason, again my apologies for late response :pray:

**Comment by alexgleason** [comment]
That's perfect. Thank you @esroyo !
